version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - IP_CAMERA_USERNAME=${IP_CAMERA_USERNAME}
      - IP_CAMERA_PASSWORD=${IP_CAMERA_PASSWORD}
    volumes:
      - ./camera_connections.json:/app/camera_connections.json
    restart: unless-stopped

volumes:
  camera_connections:

networks:
  default:
    name: camera-network