services:
  api:
    build: .
    ports:
      - "192.168.0.20:8000:8000"
    environment:
      - IP_CAMERA_USERNAME=${IP_CAMERA_USERNAME}
      - IP_CAMERA_PASSWORD=${IP_CAMERA_PASSWORD}
    volumes:
      - ./camera_connections.json:/app/camera_connections.json
    restart: unless-stopped

volumes:
  camera_connections:
  camera-network:
    driver: bridge
